### ISSUE TITLE
online MATLAB 能否直接运行测试代码

### ISSUE THREAD

**Issue by Quentin-xue** [cuixing158/OpenCVFisheyeAndDistortionTable#1]
您好，大佬，我现在用的鱼眼相机，看到使用畸变表可以校准图像。所以想尝试一下 。
请教一下，是不是在线不能运行？麻烦指导一下，同时是否方便给个联系方式。
谢谢！
![image](https://github.com/user-attachments/assets/9407c376-68db-4008-b8e6-971e99577e5a)

**Comment by cuixing158** [comment]
你好，谢谢你提出的问题，此报错信息主要是因为`cameraIntrinsics`函数是Computer Vision Toolbox™内置函数。如果你没有安装这个工具箱，那么就会报错，为考虑通用性，我现在已经[移除了该工具箱的依赖](https://github.com/cuixing158/OpenCVFisheyeAndDistortionTable/blob/71242c37ab623c77bdd493159ec0e8a41ba8e7f1/undistortFisheyeImgFromTable.m#L159)。

请重新拉取最新代码，整个代码可以在 Matlab Online上运行的。
